// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Daily_Quotes_Rest_Api;
//
//    var randomQuotes = RandomQuotes.FromJson(jsonString);

namespace Daily_Quotes_Rest_Api
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RandomQuotes
    {
        [JsonProperty("q")]
        public string Q { get; set; }

        [JsonProperty("a")]
        public string A { get; set; }

        [JsonProperty("h")]
        public string H { get; set; }
    }

    public partial class RandomQuotes
    {
        public static RandomQuotes[] FromJson(string json) => JsonConvert.DeserializeObject<RandomQuotes[]>(json, Daily_Quotes_Rest_Api.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this RandomQuotes[] self) => JsonConvert.SerializeObject(self, Daily_Quotes_Rest_Api.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
