// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Chuck_Norris_Rest_Api;
//
//    var chuckNorris = ChuckNorris.FromJson(jsonString);

namespace Chuck_Norris_Rest_Api
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ChuckNorris
    {
        [JsonProperty("categories")]
        public object[] Categories { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("icon_url")]
        public Uri IconUrl { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public partial class ChuckNorris
    {
        public static ChuckNorris FromJson(string json) => JsonConvert.DeserializeObject<ChuckNorris>(json, Chuck_Norris_Rest_Api.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ChuckNorris self) => JsonConvert.SerializeObject(self, Chuck_Norris_Rest_Api.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
